### ISSUE TITLE
Port must be an integer issue when launching the app

### ISSUE THREAD

**Issue by redlumxn** [agouz/SuperheroAPI#1]
I am in shambles. Tried to start the app and got the below error. When I remove the single quotes it magically works! This is outrageous

Line 61: `app.run(host='0.0.0.0', port=5002)`

Error
``` 
python server.py                                                                                                                                  [11:12:56]
Traceback (most recent call last):
  File "server.py", line 61, in <module>
    app.run(host='0.0.0.0', port='5002')
  File "/Users/rodmartinez/projects/anz/datathon/SuperheroAPI/venv/lib/python3.6/site-packages/flask/app.py", line 841, in run
    run_simple(host, port, self, **options)
  File "/Users/rodmartinez/projects/anz/datathon/SuperheroAPI/venv/lib/python3.6/site-packages/werkzeug/serving.py", line 733, in run_simple
    raise TypeError('port must be an integer')
TypeError: port must be an integer
(venv) 
```

**Comment by agouz** [comment]
It depends on the shirt you are wearing. I reckon you were wearing a blue shirt when you run this code, right?

It is a known issue, blue shirts only accepts integers.

Cheers
